### ISSUE TITLE
build MSAs for gene trees within genome clusters

### ISSUE THREAD

**Issue by ryneches** [ryneches/kizuchi#7]
**Problem :** Very large phylogenetic diversity will tend to "dilute" shared information in multiple sequence alignments. 

**Solution :** Build MSAs and trees for genes within each cluster. This will be more complicated to implement, but it will have superior computational scaling.

**Design :**
1. For each genome ANI clustering threshold, for each genome ANI cluster, for each gene, extract sequences from the prealignment FASTA file with the pattern `prealignments/{ANI_THRESHOLD}/{CLUSTER_ID}/{HMM}.fasta`
2. Generate useful log noting which clusters have at least two genes with enough sequences with genome linkage to carry out a correlation test. Do not write prealignment FASTA files for clusters that do not pass the required thresholds for a correlation test.
3. Using `clustalo`, for each prealignment FASTA file, create MSAs.
4. Using `trimal`, for each MSA, create filtered, trimmed alignment FASTA files.
5. Using `fasttree`, for each filtered, trimmed alignment FASTA file, create gene trees.
6. For each genome ANI clustering threshold, for each genome ANI cluster, for each pair of genes, compute tree correlation tests.

**Requirements :**
- [x] Cluster by genome ANI threshold, genome ANI cluster ID and gene
- [x] Identify genome clusters for which at least two genes have between which there are at least `MIN_CLUSTER_LINKS` genome linkages
- [x] Meaningful log output for cluster selection
- [x] Use a [checkpoint](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#data-dependent-conditional-execution) rule to write prealignment FASTA files for clusters those clusters
- [x] Define a rational output layout for output based on the cluster output
- [x] Gene alignments by genome ANI threshold, genome ANI cluster ID and gene with `clustalo`
- [x] Trim and filter alignments by genome ANI threshold, genome ANI cluster ID and gene with `trimal`
- [x] Gene tree inference by genome ANI threshold, genome ANI cluster ID and gene with `iqtree`
- [x] Use DNA alignments instead of amino acid alignments
- [x] Gene tree correlation tests by genome ANI threshold, genome ANI cluster ID and gene pair with `SuchTree`

**Comment by ryneches** [comment]
I haven't figured out how to get the wildcards to work correctly after the checkpoint. db638b1 is a workaround for this problem, but I'm going to leave this issue open until I can solve it properly.

**Comment by ryneches** [comment]
After reading [a blog post](https://evodify.com/snakemake-checkpoint-tutorial/) by @evodify, I finally realized that the wildcards argument of the input function for a post-checkpoint rule are actually usable on the second evaluation of the function after the checkpoint is run. #[061817e](https://github.com/ryneches/kizuchi/commit/061817ebfcd5d73d7c435c420e040c78c07fa656) resolves the problem and reverses the hack with sentinel files.

**Comment by ryneches** [comment]
After reading [a blog post](https://evodify.com/snakemake-checkpoint-tutorial/) by @evodify, I finally realized that the wildcards argument of the input function for a post-checkpoint rule are actually usable on the second evaluation of the function after the checkpoint is run. #[061817e](https://github.com/ryneches/kizuchi/commit/061817ebfcd5d73d7c435c420e040c78c07fa656) resolves the problem and reverses the hack with sentinel files.

**Comment by evodify** [comment]
Hi @ryneches,
I am glad my post was useful 🙂
